In [1]:
from numpy import *

In [2]:
# 产生随机数组
random.rand(4, 4)

array([[0.46385805, 0.24297718, 0.43065248, 0.36549067],
       [0.31500505, 0.27169966, 0.3490201 , 0.93812939],
       [0.29122274, 0.87629611, 0.10849496, 0.50396987],
       [0.09878035, 0.37637756, 0.75672587, 0.05273239]])

In [8]:
# 将数组转化为矩阵
randMat = mat(random.rand(4, 4))
randMat

matrix([[0.44633022, 0.70638844, 0.30854657, 0.34925207],
        [0.61570344, 0.09862037, 0.00317216, 0.07367276],
        [0.39974178, 0.75321908, 0.49429094, 0.42168802],
        [0.97697252, 0.93071453, 0.96320123, 0.00378914]])

In [9]:
# 矩阵求逆运算
invRandMat = randMat.I
invRandMat

matrix([[-0.45808519,  1.74466218,  0.07366136,  0.10319351],
        [ 6.11858433, -2.11255596, -4.70261004,  0.46022645],
        [-5.43134274,  0.26457947,  4.44769767,  0.49473175],
        [-4.12830124,  1.80945113,  5.48792787, -1.49979014]])

In [12]:
# 含有误差的单位矩阵
myEye = randMat * invRandMat
myEye

matrix([[ 1.00000000e+00,  0.00000000e+00, -4.44089210e-16,
          1.11022302e-16],
        [ 1.66533454e-16,  1.00000000e+00,  0.00000000e+00,
          9.71445147e-17],
        [-4.44089210e-16,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00],
        [ 2.28983499e-16, -9.02056208e-17,  2.56739074e-16,
          1.00000000e+00]])

In [13]:
# 构建单位矩阵
eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])